# Dataset
data_type: 'CellSeg'
train_mode: 'train_weak'
test_mode: 'val_train'
data_root: './data'
split_info: './data/splits/train_Mo_val_Mo_iter0_v5_fixed.json'

test_image_dir: './data/'
test_anno_dir: './data/'

batch_size: 4
num_worker: 4

# Augmentation
scale_range: [1.0,3.0]
crop_size: [512,512]
rand_flip: 0.5
rand_rotate: True
rand_bright: 0
rand_contrast: 0
rand_saturation: 0
rand_hue: 0
cutmix: False
beta: 1.0
cutmix_prob: 0.5
degree_version: 'v3'
degree_neighbour: 1
distance_scale: 1

# Net
net_name: 'unet'
net_num_classes: 2
net_nheads: 1
net_certainty: False
net_regression: True
net_degree: True
net_num_epoches: 500
net_learning_rate: 0.001
net_celoss: True
net_diceloss: False
net_focalloss: False
net_resume: False

# Inference
infer_stride: [256,256]
infer_threshold: 0.3
infer_seed: 0.7
test_multi_scale: [1.0]
test_fusion: 'mean'
test_degree: 315

# Saving
workspace: './workspace/Mo_Mo_v5_unet50r_cls2_1head_ep500_b4_crp512_iter0_v3'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: final.pth
val_interval: 5
save_interval: 100