# Dataset
data_type: 'CellSeg'
train_mode: 'train_weak'
test_mode: 'val_train'
data_root: './data'
split_info: './workspace/Mo_Mo_unet50r_1head_ep150_b4_crp512_iter0/label_next_iter_heat/next_iter.json'

test_image_dir: './data/'
test_anno_dir: './data/'

batch_size: 4
num_worker: 4

# Augmentation
scale_range: [0.5,3.0]
crop_size: [512,512]
rand_flip: 0.5
rand_rotate: True
rand_bright: 0
rand_contrast: 0
rand_saturation: 0
rand_hue: 0
cutmix: False
beta: 1.0
cutmix_prob: 0.5

# Net
net_name: 'unet'
net_num_classes: 2
net_nheads: 1
net_certainty: False
net_regression: True
net_num_epoches: 150
net_learning_rate: 0.001
net_celoss: True
net_diceloss: False
net_focalloss: False
net_resume: './workspace/Mo_Mo_unet50r_1head_ep150_b4_crp512_iter0/final.pth'

# Inference
infer_stride: [256,256]
infer_threshold: 0.5
test_multi_scale: [1.0]
test_fusion: 'mean'

# Saving
workspace: './workspace/Mo_Mo_unet50r_1head_ep150_b4_crp512_iter1'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: final.pth
val_interval: 5
save_interval: 100