# Dataset
data_type: 'CellSeg'
train_mode: 'train_weak'
test_mode: 'val'
data_root: './data'
split_info: './data/splits/train_pan_val_pan.json'

test_image_dir: './data/'
test_anno_dir: './data/'

batch_size: 32
num_worker: 4

# Augmentation
scale_range: [0.5,3.0]
crop_size: [256, 256]
rand_flip: 0.5
rand_rotate: True
rand_bright: 0
rand_contrast: 0
rand_saturation: 0
rand_hue: 0
cutmix: False
beta: 1.0
cutmix_prob: 0.5
degree_version: 'v10'
degree_neighbour: 1
distance_scale: 1
count_scale: 100
pesudo_rate: 0

# Net
net_name: 'unet'
net_backbone: 'resnet50'
net_num_classes: 2
net_nheads: 1
net_consistency: False
net_vorloss: False
net_convtranspose: False
net_certainty: False
net_regression: False
net_reg_weight: 1
net_degree: False
net_N: 10
net_count: False
net_num_epoches: 20
net_learning_rate: 0.001
net_celoss: True
net_diceloss: True
net_focalloss: False
net_resume: False

# Inference
infer_stride: [128,128]
infer_threshold: 0.5
infer_seed: 0.8
infer_min_area: 64
test_multi_scale: [1.0]
test_fusion: 'mean'
test_degree: 0

# Saving
workspace: './workspace/PanNuke_ablation/Pan_Pan_unet50_cls2_1head_ep20_b32_crp256_iter0'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: checkpoints/epoch_18.pth
val_interval: 1
save_interval: 5