# Dataset
data_type: 'CellSeg'
train_mode: 'train'
image_dir: './data/NeurIPS2022_CellSeg/images'
anno_dir: './data/NeurIPS2022_CellSeg/labels/iter0'
gt_dir: './data/NeurIPS2022_CellSeg/gts'
split_info: './data/NeurIPS2022_CellSeg/split_info.json'

test_image_dir: './data/NeurIPS2022_CellSeg/tuningset'
test_anno_dir: './data/NeurIPS2022_CellSeg/tuningset'

batch_size: 8
num_worker: 4

# Augmentation
scale_range: [0.5,3.0]
crop_size: [512,512]
rand_flip: 0.5
rand_rotate: True
rand_bright: 0
rand_contrast: 0
rand_saturation: 0
rand_hue: 0
cutmix: False
beta: 1.0
cutmix_prob: 0.5

# Net
net_name: 'unet'
net_num_classes: 3
net_num_epoches: 100
net_learning_rate: 0.001
net_celoss: True
net_diceloss: False
net_focalloss: False

# Inference
infer_stride: [256,256]
infer_threshold: 0.3
test_multi_scale: [0.8, 1.0, 1.2]
test_fusion: 'max'

# Saving
workspace: './workspace/debug'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: final.pth
val_interval: 5
save_interval: 30