python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50_1head_ep500_b4_crp512_iter0.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50r_1head_ep500_b4_crp512_iter0.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rv_1head_ep500_b4_crp512_iter0.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvd_1head_ep500_b4_crp512_iter0.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvdc_1head_ep500_b4_crp512_iter0.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvdc_1head_ep500_b4_crp512_iter0_cn.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50_1head_ep500_b4_crp512_full.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50r_1head_ep500_b4_crp512_full.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rv_1head_ep500_b4_crp512_full.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvd_1head_ep500_b4_crp512_full.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvdc_1head_ep500_b4_crp512_full.yaml
python run.py --train_pass True --config configs/MoNuSeg_ablation/Mo_Mo_cls2_unet50rvdc_1head_ep500_b4_crp512_full_cn.yaml