# Dataset
data_type: 'CellSeg'
train_mode: 'train_full'
test_mode: 'val_train'
data_root: './data'
split_info: './data/splits_10fold/TNBC/train_tnbc_val_tnbc_iter0_fuse_fold4.json'

test_image_dir: './data/'
test_anno_dir: './data/'

batch_size: 4
num_worker: 4

# Augmentation
scale_range: [0.5,3.0]
crop_size: [512, 512]
rand_flip: 0.5
rand_rotate: True
rand_bright: 0.1
rand_contrast: 0.1
rand_saturation: 0
rand_hue: 0
cutmix: False
beta: 1.0
cutmix_prob: 0.5
degree_version: 'v10'
degree_neighbour: 1
distance_scale: 1
count_scale: 100
pesudo_rate: 0

# Net
net_name: 'unet'
net_backbone: 'resnet50'
net_num_classes: 2
net_nheads: 1
net_consistency: True
net_vorloss: True
net_convtranspose: True
net_certainty: True
net_regression: True
net_reg_weight: 1
net_degree: True
net_N: 10
net_count: False
net_num_epoches: 300
net_learning_rate: 0.001
net_celoss: True
net_diceloss: True
net_focalloss: False
net_resume: False

# Inference
infer_stride: [256,256]
infer_threshold: 0.5
infer_seed: 0.7
test_multi_scale: [1.0]
test_fusion: 'mean'
test_degree: 0

# Saving
workspace: './workspace/TNBC_ablation/TNBC_TNBC_unet50rvdc_cls2_1head_ep300_b4_crp512_full_cn_fold4'
results_val: 'results_val'
results_test: 'results_test'
checkpoint: final.pth
val_interval: 5
save_interval: 100